Fix YAML package to 1.10
In older version of node it is raising the issue:

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

This is because the code
```
if (tag?.format) (node as Scalar).format = tag.format
```

Is not valid for older versions of node.

The code in the package can be seen here:
https://github.com/eemeli/yaml/blob/master/src/compose/compose-collection.ts#L85